# Generated by Django 4.1.2 on 2022-10-23 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('account', models.PositiveBigIntegerField(db_index=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=9)),
            ],
        ),
    ]
